villie_blog:
    resource: "@VillieBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
villie_blog_post:
    resource: "@VillieBlogBundle/Resources/config/routing/post.yml"
    prefix:   /blog
