villie_category:
    resource: "@VillieCategoryBundle/Resources/config/routing.yml"
    prefix:   /

villie_tags:
    resource: "@VillieTagsBundle/Resources/config/routing.yml"
    prefix:   /

villie_blog:
    resource: "@VillieBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
villie_blog_post:
    resource: "@VillieBlogBundle/Resources/config/routing/post.yml"
    prefix:   /blog
